
# (C) 2013 CarrierWrt.org

#
# Target: ramips
#

define Target/ramips

	CONFIG += \
		CONFIG_TARGET_ramips=y \
		CONFIG_TARGET_ROOTFS_JFFS2=n \
		CONFIG_TARGET_ramips_mt7621=y \
		CONFIG_TARGET_ramips_mt7621_DEVICE_mqmaker_witi-256m=y

	IMAGES := \
		ramips/mt7621/openwrt-ramips-mt7621-mqmaker_witi-256m-initramfs-kernel.bin \
		ramips/mt7621/openwrt-ramips-mt7621-mqmaker_witi-256m-squashfs-sysupgrade.bin

endef
