
# (C) 2013 CarrierWrt.org

#
# Target: ramips
#

define Target/ramips

	CONFIG += \
		CONFIG_TARGET_ramips=y \
		CONFIG_TARGET_ROOTFS_JFFS2=n

	IMAGES := \
		ramips/openwrt-ar71xx-generic-a02-rb-w300n-squashfs-factory.bin

endef
