
# (C) 2018 prplfoundation.org

#
# Target: intel
#


# TODO: checkout for the target code from remote git

define Target/intel

  CONFIG += \
    CONFIG_TARGET_intel_mips=y \
    CONFIG_TARGET_intel_mips_xrx500=y \
    CONFIG_TARGET_intel_mips_xrx500_Default=y \
    CONFIG_TARGET_ROOTFS_JFFS2=n \
    CONFIG_KERNEL_MODULES=y \
    CONFIG_PACKAGE_vrx518_aca_fw=y \
    CONFIG_PACKAGE_vrx518_ppe_fw=y \
    CONFIG_PACKAGE_dsl-cpe-api-vrx=y \
    CONFIG_dsl-cpe-api-vrx_MODEL_FULL=y \
    CONFIG_PACKAGE_dsl-cpe-control-vrx=y \
    CONFIG_dsl-cpe-control-vrx_MODEL_FULL=y \
    CONFIG_PACKAGE_dsl-cpe-mei-vrx=y \
    CONFIG_dsl-cpe-mei-vrx_DEVICE_VR11=y \
    CONFIG_dsl-cpe-mei-vrx_MODEL_DEBUG=y \
    CONFIG_dsl-cpe-mei-vrx_MEI_PREDEF_DBG_BAR=y \
    CONFIG_dsl-cpe-mei-vrx_MEI_DEBUG_STREAM_SUPPORT=y \
    CONFIG_dsl-cpe-mei-vrx_DTM_STANDALONE=y \
    CONFIG_dsl-cpe-mei-vrx_IRQ_POLLING_ACTIVE=y \
    CONFIG_dsl-cpe-mei-vrx_PPA_WITH_TC_CB=y \
    CONFIG_PACKAGE_dsl-vr11-firmware-xdsl=y \
    CONFIG_dsl-vr11-firmware-xdsl_FW_IN_ROOTFS=y \
    CONFIG_PACKAGE_ppacmd=y \
    CONFIG_PACKAGE_kmod-directconnect-dp=y \
    CONFIG_PACKAGE_kmod-ppa-drv=y \
    CONFIG_PACKAGE_kmod-ppa-drv-grx500=y \
    CONFIG_PACKAGE_kmod-ppa-drv-grx500-mpe=y \
    CONFIG_PACKAGE_kmod-ppa-drv-stack-al=y \
    CONFIG_PACKAGE_kmod-vrx518_ep=y \
    CONFIG_PACKAGE_kmod-vrx518_tc_drv=y \
    CONFIG_PACKAGE_kmod-ifxos=y \
    CONFIG_PACKAGE_kmod-intel_eth_drv_xrx500=y \
    CONFIG_PACKAGE_kmod-intel_eth_toe_drv_xrx500=y \
    CONFIG_PACKAGE_kmod-intel_eth_xrx500_fw=y \
    CONFIG_PACKAGE_ltq-gphy-fw-xrx5xx=y \
    %22%20CONFIG_TARGET_ar71xx_generic%20is%20not%20set \
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_A02RBW300N%20is%20not%20set \
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_A60%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ALFAAP120C%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ALFAAP96%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ALFANX%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ALL0258N%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ALL0305%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ALL0315N%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_AP121_16M%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_AP121_8M%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_AP132%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_AP135%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_AP136_010%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_AP136_020%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_AP143_16M%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_AP143_8M%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_AP147_010%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_AP152_16M%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_AP96%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_BXU2000N2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_CAP4200AG%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_DB120%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_DGL5500A1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_DHP1565A1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_DIR505A1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_DIR600A1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_DIR601A1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_DIR601B1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_DIR615C1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_DIR615E1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_DIR615E4%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_DIR615I1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_DIR615I3%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_DIR825B1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_DIR825C1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_DIR835A1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_DLRTDEV01%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_DR344%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_EAP300V2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_EAP7660D%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_EPG5000%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ESR1750%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ESR900%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_EWDORIN16M%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_EWDORINAP%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_EWDORINRT%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_F9K1115V2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_FR54RTR%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_HORNETUB%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_HORNETUBx2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_JA76PF%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_JA76PF2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_JWAP003%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_MR1750%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_MR600%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_MR900%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_MYNETREXT%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_MZKW04NU%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_MZKW300NH%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_N150R%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_NBG6616%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_NBG_460N_550N_550NH%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_OM2P%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_OM5P%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_OM5PAC%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_PB42%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_PB44%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_REALWNR1000V2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_REALWNR612V2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_TEW632BRP%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_TEW652BRP_FW%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_TEW652BRP_RECOVERY%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_TEW673GRU%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_TEW712BR%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_TEW732BR%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_TEW823DRU%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_TUBE2H16M%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_TUBE2H8M%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WHRG301N%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WHRHPG300N%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WHRHPGN%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WLAEAG300N%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WLR8100%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WNDAP360%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WNR1000V2_VC%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WNR2000%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WNR2000V4%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WNR2200%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WP543_16M%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WP543_4M%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WP543_8M%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WPE72_16M%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WPE72_4M%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WPE72_8M%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WPJ342_16M%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WPJ344_16M%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WPJ531_16M%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WPJ558_16M%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WPN824N%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WRT160NL%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WRT400N%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WRTNODE2Q%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WZR450HP2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WZR600DHP%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WZRHPAG300H%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WZRHPG300NH%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WZRHPG300NH2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_WZRHPG450H%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_YUN_16M%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_YUN_8M%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ZBTWE1526%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ZCN1523H28%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ZCN1523H516%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_antminer-s1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_antminer-s3%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_antrouter-r1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ap121f%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ap90q%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_archer-c5-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_archer-c7-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_archer-c7-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_archer-c7-v2-il%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_bhr-4grv2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_bsb%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_c-55%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_cap324%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_cap324-nocloud%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_carambola2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_cf-e316n-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_cf-e320n-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_cf-e380ac-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_cf-e380ac-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_cf-e520n%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_cf-e530n%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_cpe210-220%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_cpe510-520%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_cpe830%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_cpe870%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_cr3000%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_cr3000-nocloud%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_cr5000%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_cr5000-nocloud%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_dLAN_Hotspot%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_dLAN_pro_1200_ac%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_dLAN_pro_500_wp%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_dap-2695-a1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_dir-869-a1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_dr531%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_dragino2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_eap120%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_el-m150%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_el-mini%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_gl-ar150%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_gl-ar300%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_gl-ar300m%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_gl-domino%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_gl-inet-6408A-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_gl-inet-6416A-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_gl-mifi%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_hiwifi-hc6361%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_jwap230%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_mc-mac1200r%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_minibox-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_mr12%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_mr16%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_mw4530r-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_mynet-n600%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_mynet-n750%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_omy-g1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_omy-x1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_onion-omega%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_oolite%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_qihoo-c301%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_re450%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_rnx-n360rt%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_rw2458n%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_smart-300%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_som9331%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_sr3200%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tellstick-znet-lite%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-mr10u-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-mr11u-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-mr11u-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-mr12u-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-mr13u-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-mr3020-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-mr3040-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-mr3040-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-mr3220-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-mr3220-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-mr3420-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-mr3420-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wa701nd-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wa701nd-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wa7210n-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wa730re-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wa750re-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wa7510n%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wa801nd-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wa801nd-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wa801nd-v3%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wa830re-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wa830re-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wa850re-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wa860re-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wa901nd-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wa901nd-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wa901nd-v3%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wa901nd-v4%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wdr3320-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wdr3500-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wdr3600-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wdr4300-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wdr4300-v1-il%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wdr4310-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wdr4900-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wdr6500-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wdr7500-v3%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wpa8630%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr1041n-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr1043nd-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr1043nd-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr1043nd-v3%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr1043nd-v4%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr2543-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr703n-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr710n-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr710n-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr710n-v2.1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr720n-v3%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr720n-v4%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr740n-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr740n-v3%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr740n-v4%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr740n-v5%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr740n-v6%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr741nd-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr741nd-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr741nd-v4%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr741nd-v5%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr743nd-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr743nd-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr802n-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr810n%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr841-v1.5%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr841-v10%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr841-v11%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr841-v12%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr841-v3%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr841-v5%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr841-v7%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr841-v8%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr841-v9%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr842n-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr842n-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr842n-v3%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr843nd-v1%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr847n-v8%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr940n-v4%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr941nd-v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr941nd-v3%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr941nd-v4%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr941nd-v5%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr941nd-v6%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_tl-wr941nd-v6-cn%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ubdev01%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ubnt-air-gateway%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ubnt-air-gateway-pro%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ubnt-airrouter%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ubnt-bullet-m%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ubnt-loco-m-xw%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ubnt-ls-sr71%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ubnt-nano-m%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ubnt-nano-m-xw%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ubnt-rocket-m%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ubnt-rocket-m-ti%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ubnt-rocket-m-xw%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ubnt-rs%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ubnt-rspro%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ubnt-uap-pro%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ubnt-unifi%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ubnt-unifi-outdoor%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ubnt-unifi-outdoor-plus%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ubnt-unifiac-lite%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_ubnt-unifiac-pro%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_wbs210%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_wbs510%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_weio%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_wndr3700%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_wndr3700v2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_wndr3800%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_wndr3800ch%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_wndrmac%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_wndrmacv2%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_DEVICE_xd3200%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_generic_Default%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_mikrotik%20is%20not%20set%20\
    %22%20CONFIG_TARGET_ar71xx_nand%20is%20not%20set

endef


define Target/intel/patch
    echo "applying target patches"
    for f in $(BASE_DIR)/common/targets/intel/patches/*; do \
        (cd $(BASE_DIR)/$(OPENWRT_DIR) && patch -p1 < $$f); \
    done;
endef

define Target/intel/prepare
    
    ## remove old repo folder
    -rm -rf $(BASE_DIR)/common/targets/intel/intel_repo
    
    ## create empty repo folder
    -mkdir $(BASE_DIR)/common/targets/intel/intel_repo

    ## init repo and sync
    cd $(BASE_DIR)/common/targets/intel/intel_repo; \
    ##repo init -u https://github.com/prplfoundation/intel_repo.git -b github; \
    ##repo sync;

    # remove broken patch
    ##-rm $(BASE_DIR)/common/targets/intel/intel_repo/feed_intel/intel_mips/patches-4.9/101-revert-mips_highmem_offset.patch
    ##-rm $(BASE_DIR)/common/targets/intel/intel_repo/feed_intel/intel_mips/patches-4.9/200-add-intel-xrx500.patch

    # copy files over to openwrt build directory
    mkdir -p $(BASE_DIR)/$(OPENWRT_DIR)/dl/
    cp $(BASE_DIR)/common/targets/intel/intel_repo/dl/* $(BASE_DIR)/$(OPENWRT_DIR)/dl/

    ## add feed
    if ! grep -q "src-link feed_intel" "$(BASE_DIR)/$(OPENWRT_DIR)/feeds.conf"; then \
      echo "src-link feed_intel $(BASE_DIR)/common/targets/intel/intel_repo/feed_intel" >> $(BASE_DIR)/$(OPENWRT_DIR)/feeds.conf; \
    fi
   
    ## patch openwrt folder
    $(call Target/intel/patch)
    
    ## update the feeds and install needed packages
    cd $(BASE_DIR)/$(OPENWRT_DIR)/; \
    ./scripts/feeds update -a; \
    ./scripts/feeds install intel_mips ltq_fw_PHY_IP luci dsl-vr11-firmware-xdsl dsl-cpe-mei-vrx dsl-cpe-api-vrx dsl-cpe-control-vrx ifxos directconnect_dp vrx518_aca_fw vrx518_ppe_fw vrx518_tc_drv ppa;
    rm -rf $(BASE_DIR)/$(OPENWRT_DIR)/tmp/

endef
